version: '3'
services:
        web:
                image: tngc_flask_v1
                build: .
                ports:
                        - "8036:8080"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
