version: '3'
services:
      web:
              image: tgddkp_flask_v2
              build: .
              ports:
                      - "80869:8080"
              volumes:
                      - persistent_volume:/app/volumes
              restart: unless-stopped
volumes:
persistent_volume:
  driver: local
  driver_opts:
    o: bind
    type: none
    device: /home/ubuntu/TGDDKPFlask/volumes
