version: '3'
services:
        web:
                image: tgddkp_flask_v2
                build: .
                ports:
                        - "8069:8080"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped